name: appointement
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.9
  permission_handler: ^11.3.1
  flutter_contacts: ^1.1.9+2
  intl_phone_field: ^3.2.0
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  url_launcher: ^6.3.1
  cloud_firestore: ^5.6.2
  timezone: ^0.10.0
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^4.0.0
  shared_preferences: ^2.4.0
  firebase_storage: ^12.4.1
  image_picker: ^1.1.2
  uuid: ^4.0.0
  scrollable_positioned_list: ^0.3.5
  shimmer: ^3.0.0
  flutter_slidable: ^4.0.0
  stacked: ^3.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true